apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: roboshop-ebs
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nginx-data
  nodeSelector:
      topology.kubernetes.io/zone: us-east-1b
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
     claimName: ebs-dynamic


