apiVersion: v1
kind: Pod
metadata:
  name: labels
  #namespace: roboshop
  labels:
   project: roboshop
   env: dev
   component: frontend
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
    
