apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  annotations:
    imageregistry: "https://hub.docker.com/"
    gitrepo: "https://github.com/sowjanya88s/k8s-resources.git"
spec:
  containers:
  - name: nginx
    image: nginx
    