apiVersion: v1
kind: Service
metadata:
  name: nodeport-nginx
spec:
  type: NodePort
  selector:
    project: roboshop
    env: dev
    component: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30873