apiVersion: v1
kind: Service
metadata:
  name: svc-lb
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    env: dev
    component: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007