apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    project: roboshop
    env: dev
    component: frontend 
  #annotations:
    #kubernetes.io/change-cause: "moving to 1.29.7"
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      env: dev
      component: frontend 
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        component: frontend 
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine3.23-perl
        
